// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name must match first type name", Justification = "<Pending>", Scope = "type", Target = "~T:Microsoft.Azure.WebJobs.Script.Tests.ITestInterface")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1636:File header copyright text must match", Justification = "<Pending>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1008:Opening parenthesis must be spaced correctly", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Azure.WebJobs.Script.Tests.Controllers.Admin.SwaggerControllerTests.GetTestTargets(System.Collections.ObjectModel.Collection{Microsoft.Azure.WebJobs.Script.Description.FunctionDescriptor},System.Boolean)~System.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1008:Opening parenthesis must be spaced correctly", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Azure.WebJobs.Script.Tests.Controllers.Admin.SwaggerControllerTests.GetTestTargets(System.Collections.ObjectModel.Collection{Microsoft.Azure.WebJobs.Script.Description.FunctionDescriptor},System.Boolean)~System.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis must be spaced correctly", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.Azure.WebJobs.Script.Tests.Controllers.Admin.SwaggerControllerTests.GetTestTargets(System.Collections.ObjectModel.Collection{Microsoft.Azure.WebJobs.Script.Description.FunctionDescriptor},System.Boolean)~System.")]